config/routes.rb
# typed: strict
Rails.application.routes.draw do
  root 'list#react'
  resources :list, only: :index
  resources :products
  resources :discounts

  resources :locations do
    collection do
      post 'search'
    end
  end

  resource :refresh, only: :show do
    post :discount
    post :store
    post :all
    post :soft_all
    post :all_store
  end

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
end

app/models/application_record.rb
# typed: false
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/discount.rb
# typed: false
class Discount < ApplicationRecord
  has_many :discount_product_type_groups, dependent: :delete_all
  has_many :products, through: :discount_product_type_groups
  belongs_to :store

  default_scope { where(removed: false) }
end

app/models/discount_product_type.rb
# typed: false
class DiscountProductType < ApplicationRecord
  belongs_to :product
  belongs_to :discount_product_type_group

  def ==(other)
    other.class == self.class &&
      other.product_type == product_type
  end
end

app/models/discount_product_type_group.rb
# typed: false
class DiscountProductTypeGroup < ApplicationRecord
  belongs_to :discount
  has_many :discount_product_types, dependent: :delete_all
  has_many :products, through: :discount_product_types

  def ==(other)
    other.class == self.class &&
      other.required_quantity == required_quantity &&
      other.max_quantity == max_quantity &&
      other.group_type == group_type &&
      other.discount_product_types == discount_product_types
  end
end

app/models/location_builder.rb
# typed: true
# frozen_string_literal: true

class LocationBuilder
  include ActiveModel::Model

  attr_accessor :city
  attr_accessor :postal_code
  attr_accessor :province
  attr_accessor :address
end

app/models/product.rb
# typed: false
class Product < ApplicationRecord
  has_many :discount_product_types
  has_many :discount_product_type_groups, through: :discount_product_types
end

app/models/product_type.rb
# typed: false
class ProductType < ApplicationRecord
  has_many :discount_product_types
  has_many :discount_product_type_groups, through: :discount_product_types
end

app/models/store.rb
# typed: false
class Store < ApplicationRecord
  has_many :discounts
end

app/controllers/application_controller.rb
# typed: strong
class ApplicationController < ActionController::Base
end

app/controllers/graphql_controller.rb
# typed: false
class GraphqlController < ApplicationController
  protect_from_forgery with: :null_session

  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = SuperGreatPizzaSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue => e
    raise e unless Rails.env.development?
    handle_error_in_development e
  end

  private

  # Handle form data, JSON body, or a blank value
  def ensure_hash(ambiguous_param)
    case ambiguous_param
    when String
      if ambiguous_param.present?
        ensure_hash(JSON.parse(ambiguous_param))
      else
        {}
      end
    when Hash, ActionController::Parameters
      ambiguous_param
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { error: { message: e.message, backtrace: e.backtrace }, data: {} }, status: 500
  end
end

app/controllers/list_controller.rb
# typed: true
class ListController < ApplicationController
  def index
    @q = Discount.ransack(params[:q])
    @discounts = @q.result(distinct: true).includes(:products, :discount_product_type_groups, :store)
  end
end

app/controllers/locations_controller.rb
# typed: true
# frozen_string_literal: true

require_relative '../../lib/labelling_form_builder'

class LocationsController < ApplicationController
  def index
    @location = LocationBuilder.new
  end

  def search
    locations = Fetchers::LocationService.new(
      **location_params.to_h.symbolize_keys
    ).fetch

    locations.each do |location|
      Fetchers::StoreService.new(
        store_id: location.store_id,
        address: location.address
      ).fetch
    end

    redirect_to root_path(q: {
      store_id_eq: Store.find_by(code: locations.find(&:can_deliver?).store_id)
    })
  end

  def location_params
    params
      .fetch('location_builder')
      .permit(:city, :postal_code, :province, :address)
  end
end

app/controllers/refreshes_controller.rb
# typed: false
class RefreshesController < ApplicationController
  def show
  end

  def discount
    store_id = params.fetch(:store_id)
    code = params.fetch(:code)
    FetchDiscountJob.perform_later(code, store_id)
    redirect_to refresh_path
  end

  def store
    store_id = params.fetch(:store_id)
    FetchStoreJob.perform_later(store_id)
    redirect_to refresh_path
  end

  def all
    Discount.pluck(:code, :store_id).each do |code, store_id|
      FetchDiscountJob.perform_later(code, store_id)
    end
    redirect_to refresh_path
  end

  def soft_all
    Discount.pluck(:json).each do |json|
      FetcherService.new.process_discount(json)
    end
    redirect_to refresh_path
  end

  def all_store
    FetcherService.call(params.fetch(:store_id))
    redirect_to refresh_path
  end
end

app/helpers/api_helper.rb
# typed: true
require 'net/http'

module ApiHelper
  def query(url)
    url = URI(url)

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    request = Net::HTTP::Get.new(url)
    request["pragma"] = 'no-cache'
    request["dpz-language"] = 'en'
    request["accept-language"] = 'en-US,en;q=0.9,en-CA;q=0.8'
    request["user-agent"] = 'Mozilla/5.0 (X11; Windows x86_64) AppleWebKit/520.92 (KHTML, like Gecko) Chrome/60.0.1974.20 Safari/520.92'
    request["accept"] = 'application/json, text/javascript, */*; q=0.01'
    request["dpz-market"] = 'CANADA'
    request["cache-control"] = 'no-cache'
    request["referer"] = 'https://order.dominos.ca/assets/build/xdomain/proxy.html'
    request["market"] = 'CANADA'
    request["connection"] = 'keep-alive'

    http.request(request)
  end
end

app/helpers/application_helper.rb
# typed: strong
module ApplicationHelper
end

app/helpers/list_helper.rb
# typed: strong
module ListHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuperGreatPizza</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= tag.meta name: "referrer", content: "same-origin" %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# <%= stylesheet_pack_tag 'application' %1> %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/list/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Discounts with info</h1>

<%= search_form_for @q, url: list_index_path do |f| %>
  <%= f.label 'store id' %>
  <%= f.collection_select :store_id_eq, Store.all, :id, :address, include_blank: true %>

  <%= f.label 'discount code' %>
  <%= f.search_field :code_eq %>

  <%= f.label 'Product Name' %>
  <%= f.collection_select :products_id_eq, Product.all, :id, :name, include_blank: true %>

  <%= f.label 'Minimum Required' %>
  <%= f.search_field :discount_product_type_groups_required_quantity_lteq %>
  <%= f.submit %>
<% end %>

<%= tag.p @q.inspect %>

<%= tag.table do %>
  <%= tag.thead do %>
    <%= tag.tr do %>
      <%= tag.th '' %>
      <%= tag.th 'Price' %>
      <%= tag.th 'Code' %>
      <%= tag.th 'Name' %>
    <% end %>
  <% end %>

  <%= tag.tbody do %>
    <% @discounts.each do |discount| %>
      <%= tag.tr do %>
        <%= tag.td tag.image src: discount.image_url %>
        <%= tag.td tag.h3 discount.name %>
        <%= tag.td "$#{discount.price}" %>
        <%= tag.td discount.code %>

        <%= tag.table do %>
          <%= tag.thead do %>
            <%= tag.th 'Type' %>
            <%= tag.th 'Min required' %>
            <%= tag.th 'Max required' %>
          <% end %>

          <%= tag.tbody do %>
            <% discount.discount_product_type_groups.each do |group| %>
              <%= tag.tr do %>
                <%= tag.td group.group_type %>
                <%= tag.td group.required_quantity %>
                <%= tag.td group.max_quantity %>
                <%= tag.td group.products.map(&:code).join(', ') %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/list/react.html.erb
<div id="root" />
<%= javascript_pack_tag 'application' %>

app/views/locations/index.html.erb
<%= form_for @location, url: { action: 'search' }, builder: LabellingFormBuilder do |form| %>
  <%= form.text_field :city %>
  <%= form.text_field :postal_code %>
  <%= form.text_field :province %>
  <%= form.text_field :address %>

  <%= form.submit 'Search' %>
<% end %>

app/views/refreshes/show.html.erb
<h1>Refresh</h1>

<h3>Fetch a discount for a store</h3>
<%= form_tag :discount_refresh do %>
  <%= label_tag :code, 'Discount code' %>
  <%= text_field_tag :code %>
  <%= label_tag :store_id, 'Store ID' %>
  <%= text_field_tag :store_id %>
  <%= submit_tag :Fetch %>
<% end %>

<h3>Refresh a store's existing discounts</h3>
<%= form_tag :store_refresh do %>
  <%= label_tag :store_id, 'Store ID' %>
  <%= text_field_tag :store_id %>
  <%= submit_tag :Refresh %>
<% end %>

<h3>Fetch new discounts for a store</h3>
<%= form_tag :all_store_refresh do %>
  <%= label_tag :store_id, 'Store ID' %>
  <%= text_field_tag :store_id %>
  <%= submit_tag :Fetch %>
<% end %>

<h3>Refresh all discounts</h3>
<%= form_tag :all_refresh do %>
  <%= submit_tag :Fetch %>
<% end %>

<h3>Refresh all discounts (using saved data only)<h3>
<%= form_tag :soft_all_refresh do %>
  <%= submit_tag :Refresh %>
<% end %>